version: "3.5"

services:
  service-sql:
    image: mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04 
    environment: 
    - ACCEPT_EULA=Y
    - MSSQL_SA_PASSWORD=BDasr#123456 
    ports:
    - 1434:1433
    restart: always 
    container_name: sqlASR 
    networks:
    - asr
networks:
  asr:
    name: micra