// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI_MVC_ASR.Datos;

#nullable disable

namespace WebAPI_MVC_ASR.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240906204457_actualizacionTablas")]
    partial class actualizacionTablas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAPI_MVC_ASR.Models.Feed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("HourlyImbalanceFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ImbalanceFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PeakLoadFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Timestamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimestampUTC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("VolumeFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("WeeklyFee")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Feeds");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "NO",
                            Timestamp = "2017-05-01T00:00:00",
                            TimestampUTC = "2017-04-30T22:00:00Z",
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 2,
                            Country = "FI",
                            Timestamp = "2017-05-01T00:00:00",
                            TimestampUTC = "2017-04-30T22:00:00Z",
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 3,
                            Country = "SE",
                            PeakLoadFee = 0.43m,
                            Timestamp = "2017-05-01T00:00:00",
                            TimestampUTC = "2017-04-30T22:00:00Z",
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 4,
                            Country = "DK",
                            Timestamp = "2017-05-01T00:00:00",
                            TimestampUTC = "2017-04-30T22:00:00Z",
                            WeeklyFee = 0
                        },
                        new
                        {
                            Id = 5,
                            Country = "SE",
                            PeakLoadFee = 0.43m,
                            Timestamp = "2018-11-15T23:00:00",
                            TimestampUTC = "2018-11-15T22:00:00Z",
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 6,
                            Country = "SE",
                            PeakLoadFee = 0.35m,
                            Timestamp = "2018-11-16T00:00:00",
                            TimestampUTC = "2018-11-15T23:00:00Z",
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 7,
                            Country = "SE",
                            PeakLoadFee = 0.35m,
                            Timestamp = "2019-11-15T23:00:00",
                            TimestampUTC = "2019-11-15T22:00:00Z",
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 8,
                            Country = "SE",
                            PeakLoadFee = 0.31m,
                            Timestamp = "2019-11-16T00:00:00",
                            TimestampUTC = "2019-11-15T23:00:00Z",
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 9,
                            Country = "SE",
                            PeakLoadFee = 0.31m,
                            Timestamp = "2020-11-15T23:00:00",
                            TimestampUTC = "2020-11-15T22:00:00Z",
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 10,
                            Country = "SE",
                            PeakLoadFee = 0.27m,
                            Timestamp = "2020-11-16T00:00:00",
                            TimestampUTC = "2020-11-15T23:00:00Z",
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 11,
                            Country = "DK",
                            Timestamp = "2021-01-31T23:00:00",
                            TimestampUTC = "2021-01-31T22:00:00Z",
                            WeeklyFee = 0
                        },
                        new
                        {
                            Id = 12,
                            Country = "DK",
                            Timestamp = "2021-02-01T00:00:00",
                            TimestampUTC = "2021-01-31T23:00:00Z",
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 13,
                            Country = "SE",
                            PeakLoadFee = 0.27m,
                            Timestamp = "2021-10-31T23:00:00",
                            TimestampUTC = "2021-10-31T22:00:00Z",
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 14,
                            Country = "NO",
                            Timestamp = "2021-10-31T23:00:00",
                            TimestampUTC = "2021-10-31T22:00:00Z",
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 15,
                            Country = "FI",
                            Timestamp = "2021-10-31T23:00:00",
                            TimestampUTC = "2021-10-31T22:00:00Z",
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 16,
                            Country = "DK",
                            Timestamp = "2021-10-31T23:00:00",
                            TimestampUTC = "2021-10-31T22:00:00Z",
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 17,
                            Country = "FI",
                            ImbalanceFee = 1.15m,
                            Timestamp = "2021-11-01T00:00:00",
                            TimestampUTC = "2021-10-31T23:00:00Z",
                            VolumeFee = 0.36m,
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 18,
                            Country = "SE",
                            ImbalanceFee = 1.15m,
                            PeakLoadFee = 0.27m,
                            Timestamp = "2021-11-01T00:00:00",
                            TimestampUTC = "2021-10-31T23:00:00Z",
                            VolumeFee = 0.85m,
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 19,
                            Country = "NO",
                            ImbalanceFee = 1.15m,
                            Timestamp = "2021-11-01T00:00:00",
                            TimestampUTC = "2021-10-31T23:00:00Z",
                            VolumeFee = 0.08m,
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 20,
                            Country = "DK",
                            ImbalanceFee = 0.133m,
                            Timestamp = "2021-11-01T00:00:00",
                            TimestampUTC = "2021-10-31T23:00:00Z",
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 21,
                            Country = "SE",
                            ImbalanceFee = 1.15m,
                            PeakLoadFee = 0.27m,
                            Timestamp = "2021-11-15T23:00:00",
                            TimestampUTC = "2021-11-15T22:00:00Z",
                            VolumeFee = 0.85m,
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 22,
                            Country = "SE",
                            ImbalanceFee = 1.15m,
                            PeakLoadFee = 0.32m,
                            Timestamp = "2021-11-16T00:00:00",
                            TimestampUTC = "2021-11-15T23:00:00Z",
                            VolumeFee = 0.85m,
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 23,
                            Country = "FI",
                            ImbalanceFee = 1.15m,
                            Timestamp = "2022-01-31T22:00:00",
                            TimestampUTC = "2022-01-31T21:00:00Z",
                            VolumeFee = 0.36m,
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 24,
                            Country = "FI",
                            ImbalanceFee = 1.15m,
                            Timestamp = "2022-01-31T23:00:00",
                            TimestampUTC = "2022-01-31T22:00:00Z",
                            VolumeFee = 0.41m,
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 25,
                            Country = "FI",
                            ImbalanceFee = 1.15m,
                            Timestamp = "2022-04-30T22:00:00",
                            TimestampUTC = "2022-04-30T20:00:00Z",
                            VolumeFee = 0.41m,
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 26,
                            Country = "FI",
                            ImbalanceFee = 1.15m,
                            Timestamp = "2022-04-30T23:00:00",
                            TimestampUTC = "2022-04-30T21:00:00Z",
                            VolumeFee = 0.64m,
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 27,
                            Country = "NO",
                            ImbalanceFee = 1.15m,
                            Timestamp = "2022-05-31T23:00:00",
                            TimestampUTC = "2022-05-31T21:00:00Z",
                            VolumeFee = 0.08m,
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 28,
                            Country = "NO",
                            ImbalanceFee = 1.15m,
                            Timestamp = "2022-06-01T00:00:00",
                            TimestampUTC = "2022-05-31T22:00:00Z",
                            VolumeFee = 0.13m,
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 29,
                            Country = "FI",
                            ImbalanceFee = 1.15m,
                            Timestamp = "2022-08-31T22:00:00",
                            TimestampUTC = "2022-08-31T20:00:00Z",
                            VolumeFee = 0.64m,
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 30,
                            Country = "FI",
                            ImbalanceFee = 1.15m,
                            Timestamp = "2022-08-31T23:00:00",
                            TimestampUTC = "2022-08-31T21:00:00Z",
                            VolumeFee = 1.2m,
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 31,
                            Country = "SE",
                            ImbalanceFee = 1.15m,
                            PeakLoadFee = 0.32m,
                            Timestamp = "2022-11-15T23:00:00",
                            TimestampUTC = "2022-11-15T22:00:00Z",
                            VolumeFee = 0.85m,
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 32,
                            Country = "SE",
                            ImbalanceFee = 1.15m,
                            PeakLoadFee = 0.33m,
                            Timestamp = "2022-11-16T00:00:00",
                            TimestampUTC = "2022-11-15T23:00:00Z",
                            VolumeFee = 0.85m,
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 33,
                            Country = "FI",
                            ImbalanceFee = 1.15m,
                            Timestamp = "2022-12-31T23:00:00",
                            TimestampUTC = "2022-12-31T22:00:00Z",
                            VolumeFee = 1.7m,
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 34,
                            Country = "SE",
                            ImbalanceFee = 1.15m,
                            PeakLoadFee = 0.33m,
                            Timestamp = "2022-12-31T23:00:00",
                            TimestampUTC = "2022-12-31T22:00:00Z",
                            VolumeFee = 0.85m,
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 35,
                            Country = "SE",
                            ImbalanceFee = 1.15m,
                            PeakLoadFee = 0.33m,
                            Timestamp = "2023-01-01T00:00:00",
                            TimestampUTC = "2022-12-31T23:00:00Z",
                            VolumeFee = 1.2m,
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 36,
                            Country = "FI",
                            ImbalanceFee = 1.15m,
                            Timestamp = "2023-04-30T22:00:00",
                            TimestampUTC = "2023-04-30T20:00:00Z",
                            VolumeFee = 1.7m,
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 37,
                            Country = "NO",
                            ImbalanceFee = 1.15m,
                            Timestamp = "2023-05-21T23:00:00",
                            TimestampUTC = "2023-05-21T21:00:00Z",
                            VolumeFee = 0.13m,
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 38,
                            Country = "FI",
                            ImbalanceFee = 1.15m,
                            Timestamp = "2023-05-21T23:00:00",
                            TimestampUTC = "2023-05-21T21:00:00Z",
                            VolumeFee = 1.2m,
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 39,
                            Country = "DK",
                            ImbalanceFee = 0.133m,
                            Timestamp = "2023-05-21T23:00:00",
                            TimestampUTC = "2023-05-21T21:00:00Z",
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 40,
                            Country = "SE",
                            ImbalanceFee = 1.15m,
                            PeakLoadFee = 0.33m,
                            Timestamp = "2023-05-21T23:00:00",
                            TimestampUTC = "2023-05-21T21:00:00Z",
                            VolumeFee = 1.2m,
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 41,
                            Country = "NO",
                            HourlyImbalanceFee = 1.15m,
                            Timestamp = "2023-06-01T00:00:00",
                            TimestampUTC = "2023-05-31T22:00:00Z",
                            VolumeFee = 0.13m,
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 42,
                            Country = "SE",
                            HourlyImbalanceFee = 1.15m,
                            PeakLoadFee = 0.33m,
                            Timestamp = "2023-06-01T00:00:00",
                            TimestampUTC = "2023-05-31T22:00:00Z",
                            VolumeFee = 1.2m,
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 43,
                            Country = "DK",
                            HourlyImbalanceFee = 0.133m,
                            Timestamp = "2023-06-01T00:00:00",
                            TimestampUTC = "2023-05-31T22:00:00Z",
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 44,
                            Country = "FI",
                            HourlyImbalanceFee = 1.15m,
                            Timestamp = "2023-06-01T00:00:00",
                            TimestampUTC = "2023-05-31T22:00:00Z",
                            VolumeFee = 1.2m,
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 45,
                            Country = "FI",
                            HourlyImbalanceFee = 1.15m,
                            Timestamp = "2023-10-31T22:00:00",
                            TimestampUTC = "2023-10-31T21:00:00Z",
                            VolumeFee = 1.2m,
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 46,
                            Country = "FI",
                            HourlyImbalanceFee = 1.15m,
                            Timestamp = "2023-10-31T23:00:00",
                            TimestampUTC = "2023-10-31T22:00:00Z",
                            VolumeFee = 1.5m,
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 47,
                            Country = "SE",
                            HourlyImbalanceFee = 1.15m,
                            PeakLoadFee = 0.33m,
                            Timestamp = "2023-11-15T23:00:00",
                            TimestampUTC = "2023-11-15T22:00:00Z",
                            VolumeFee = 1.2m,
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 48,
                            Country = "SE",
                            HourlyImbalanceFee = 1.15m,
                            PeakLoadFee = 0.29m,
                            Timestamp = "2023-11-16T00:00:00",
                            TimestampUTC = "2023-11-15T23:00:00Z",
                            VolumeFee = 1.2m,
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 49,
                            Country = "NO",
                            HourlyImbalanceFee = 1.15m,
                            Timestamp = "2023-12-31T23:00:00",
                            TimestampUTC = "2023-12-31T22:00:00Z",
                            VolumeFee = 0.13m,
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 50,
                            Country = "SE",
                            HourlyImbalanceFee = 1.15m,
                            PeakLoadFee = 0.29m,
                            Timestamp = "2023-12-31T23:00:00",
                            TimestampUTC = "2023-12-31T22:00:00Z",
                            VolumeFee = 1.2m,
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 51,
                            Country = "SE",
                            HourlyImbalanceFee = 1.15m,
                            PeakLoadFee = 0.29m,
                            Timestamp = "2024-01-01T00:00:00",
                            TimestampUTC = "2023-12-31T23:00:00Z",
                            VolumeFee = 1.6m,
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 52,
                            Country = "NO",
                            HourlyImbalanceFee = 1.15m,
                            Timestamp = "2024-01-01T00:00:00",
                            TimestampUTC = "2023-12-31T23:00:00Z",
                            VolumeFee = 0.21m,
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 53,
                            Country = "FI",
                            HourlyImbalanceFee = 1.15m,
                            Timestamp = "2024-02-29T22:00:00",
                            TimestampUTC = "2024-02-29T21:00:00Z",
                            VolumeFee = 1.5m,
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 54,
                            Country = "FI",
                            HourlyImbalanceFee = 1.15m,
                            Timestamp = "2024-02-29T23:00:00",
                            TimestampUTC = "2024-02-29T22:00:00Z",
                            VolumeFee = 1.33m,
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 55,
                            Country = "SE",
                            HourlyImbalanceFee = 1.15m,
                            PeakLoadFee = 0.29m,
                            Timestamp = "2024-09-01T23:00:00",
                            TimestampUTC = "2024-09-01T21:00:00Z",
                            VolumeFee = 1.6m,
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 56,
                            Country = "NO",
                            HourlyImbalanceFee = 1.15m,
                            Timestamp = "2024-09-01T23:00:00",
                            TimestampUTC = "2024-09-01T21:00:00Z",
                            VolumeFee = 0.21m,
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 57,
                            Country = "DK",
                            HourlyImbalanceFee = 0.133m,
                            Timestamp = "2024-09-01T23:00:00",
                            TimestampUTC = "2024-09-01T21:00:00Z",
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 58,
                            Country = "FI",
                            HourlyImbalanceFee = 1.15m,
                            Timestamp = "2024-09-01T23:00:00",
                            TimestampUTC = "2024-09-01T21:00:00Z",
                            VolumeFee = 1.33m,
                            WeeklyFee = 30
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
