// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI_MVC_ASR.Datos;

#nullable disable

namespace WebAPI_MVC_ASR.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240906144523_AlimentartablaFeeds1")]
    partial class AlimentartablaFeeds1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAPI_MVC_ASR.Models.Feed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("HourlyImbalanceFee")
                        .HasColumnType("real");

                    b.Property<float?>("ImbalanceFee")
                        .HasColumnType("real");

                    b.Property<float?>("PeakLoadFee")
                        .HasColumnType("real");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("TimestampUTC")
                        .HasColumnType("datetimeoffset");

                    b.Property<float?>("VolumeFee")
                        .HasColumnType("real");

                    b.Property<int>("WeeklyFee")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Feeds");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "NO",
                            Timestamp = new DateTimeOffset(new DateTime(2017, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            TimestampUTC = new DateTimeOffset(new DateTime(2017, 4, 30, 22, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 2,
                            Country = "FI",
                            Timestamp = new DateTimeOffset(new DateTime(2017, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            TimestampUTC = new DateTimeOffset(new DateTime(2017, 4, 30, 22, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 3,
                            Country = "SE",
                            PeakLoadFee = 0.43f,
                            Timestamp = new DateTimeOffset(new DateTime(2017, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            TimestampUTC = new DateTimeOffset(new DateTime(2017, 4, 30, 22, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 4,
                            Country = "DK",
                            Timestamp = new DateTimeOffset(new DateTime(2017, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            TimestampUTC = new DateTimeOffset(new DateTime(2017, 4, 30, 22, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            WeeklyFee = 0
                        },
                        new
                        {
                            Id = 5,
                            Country = "SE",
                            PeakLoadFee = 0.43f,
                            Timestamp = new DateTimeOffset(new DateTime(2018, 11, 15, 23, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            TimestampUTC = new DateTimeOffset(new DateTime(2018, 11, 15, 22, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 6,
                            Country = "SE",
                            PeakLoadFee = 0.35f,
                            Timestamp = new DateTimeOffset(new DateTime(2018, 11, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            TimestampUTC = new DateTimeOffset(new DateTime(2018, 11, 15, 23, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 7,
                            Country = "SE",
                            PeakLoadFee = 0.35f,
                            Timestamp = new DateTimeOffset(new DateTime(2019, 11, 15, 23, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            TimestampUTC = new DateTimeOffset(new DateTime(2019, 11, 15, 22, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 8,
                            Country = "SE",
                            PeakLoadFee = 0.31f,
                            Timestamp = new DateTimeOffset(new DateTime(2019, 11, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            TimestampUTC = new DateTimeOffset(new DateTime(2019, 11, 15, 23, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 9,
                            Country = "SE",
                            PeakLoadFee = 0.31f,
                            Timestamp = new DateTimeOffset(new DateTime(2020, 11, 15, 23, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            TimestampUTC = new DateTimeOffset(new DateTime(2020, 11, 15, 22, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 10,
                            Country = "SE",
                            PeakLoadFee = 0.27f,
                            Timestamp = new DateTimeOffset(new DateTime(2020, 11, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            TimestampUTC = new DateTimeOffset(new DateTime(2020, 11, 15, 23, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 11,
                            Country = "DK",
                            Timestamp = new DateTimeOffset(new DateTime(2021, 1, 31, 23, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            TimestampUTC = new DateTimeOffset(new DateTime(2021, 1, 31, 22, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            WeeklyFee = 0
                        },
                        new
                        {
                            Id = 12,
                            Country = "DK",
                            Timestamp = new DateTimeOffset(new DateTime(2021, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            TimestampUTC = new DateTimeOffset(new DateTime(2021, 1, 31, 23, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 13,
                            Country = "SE",
                            PeakLoadFee = 0.27f,
                            Timestamp = new DateTimeOffset(new DateTime(2021, 10, 31, 23, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            TimestampUTC = new DateTimeOffset(new DateTime(2021, 10, 31, 22, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 14,
                            Country = "NO",
                            Timestamp = new DateTimeOffset(new DateTime(2021, 10, 31, 23, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            TimestampUTC = new DateTimeOffset(new DateTime(2021, 10, 31, 22, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 15,
                            Country = "FI",
                            Timestamp = new DateTimeOffset(new DateTime(2021, 10, 31, 23, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            TimestampUTC = new DateTimeOffset(new DateTime(2021, 10, 31, 22, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 16,
                            Country = "DK",
                            Timestamp = new DateTimeOffset(new DateTime(2021, 10, 31, 23, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            TimestampUTC = new DateTimeOffset(new DateTime(2021, 10, 31, 22, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 17,
                            Country = "FI",
                            ImbalanceFee = 1.15f,
                            Timestamp = new DateTimeOffset(new DateTime(2021, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            TimestampUTC = new DateTimeOffset(new DateTime(2021, 10, 31, 23, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            VolumeFee = 0.36f,
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 18,
                            Country = "SE",
                            ImbalanceFee = 1.15f,
                            PeakLoadFee = 0.27f,
                            Timestamp = new DateTimeOffset(new DateTime(2021, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            TimestampUTC = new DateTimeOffset(new DateTime(2021, 10, 31, 23, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            VolumeFee = 0.85f,
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 19,
                            Country = "NO",
                            ImbalanceFee = 1.15f,
                            Timestamp = new DateTimeOffset(new DateTime(2021, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            TimestampUTC = new DateTimeOffset(new DateTime(2021, 10, 31, 23, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            VolumeFee = 0.08f,
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 20,
                            Country = "DK",
                            ImbalanceFee = 0.133f,
                            Timestamp = new DateTimeOffset(new DateTime(2021, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            TimestampUTC = new DateTimeOffset(new DateTime(2021, 10, 31, 23, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 21,
                            Country = "SE",
                            ImbalanceFee = 1.15f,
                            PeakLoadFee = 0.27f,
                            Timestamp = new DateTimeOffset(new DateTime(2021, 11, 15, 23, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            TimestampUTC = new DateTimeOffset(new DateTime(2021, 11, 15, 22, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            VolumeFee = 0.85f,
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 22,
                            Country = "SE",
                            ImbalanceFee = 1.15f,
                            PeakLoadFee = 0.32f,
                            Timestamp = new DateTimeOffset(new DateTime(2021, 11, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            TimestampUTC = new DateTimeOffset(new DateTime(2021, 11, 15, 23, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            VolumeFee = 0.85f,
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 23,
                            Country = "FI",
                            ImbalanceFee = 1.15f,
                            Timestamp = new DateTimeOffset(new DateTime(2022, 1, 31, 22, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            TimestampUTC = new DateTimeOffset(new DateTime(2022, 1, 31, 21, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            VolumeFee = 0.36f,
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 24,
                            Country = "FI",
                            ImbalanceFee = 1.15f,
                            Timestamp = new DateTimeOffset(new DateTime(2022, 1, 31, 23, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            TimestampUTC = new DateTimeOffset(new DateTime(2022, 1, 31, 22, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            VolumeFee = 0.41f,
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 25,
                            Country = "FI",
                            ImbalanceFee = 1.15f,
                            Timestamp = new DateTimeOffset(new DateTime(2022, 4, 30, 22, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            TimestampUTC = new DateTimeOffset(new DateTime(2022, 4, 30, 20, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            VolumeFee = 0.41f,
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 26,
                            Country = "FI",
                            ImbalanceFee = 1.15f,
                            Timestamp = new DateTimeOffset(new DateTime(2022, 4, 30, 23, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            TimestampUTC = new DateTimeOffset(new DateTime(2022, 4, 30, 21, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            VolumeFee = 0.64f,
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 27,
                            Country = "NO",
                            ImbalanceFee = 1.15f,
                            Timestamp = new DateTimeOffset(new DateTime(2022, 5, 31, 23, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            TimestampUTC = new DateTimeOffset(new DateTime(2022, 5, 31, 21, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            VolumeFee = 0.08f,
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 28,
                            Country = "NO",
                            ImbalanceFee = 1.15f,
                            Timestamp = new DateTimeOffset(new DateTime(2022, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            TimestampUTC = new DateTimeOffset(new DateTime(2022, 5, 31, 22, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            VolumeFee = 0.13f,
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 29,
                            Country = "FI",
                            ImbalanceFee = 1.15f,
                            Timestamp = new DateTimeOffset(new DateTime(2022, 8, 31, 22, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            TimestampUTC = new DateTimeOffset(new DateTime(2022, 8, 31, 20, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            VolumeFee = 0.64f,
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 30,
                            Country = "FI",
                            ImbalanceFee = 1.15f,
                            Timestamp = new DateTimeOffset(new DateTime(2022, 8, 31, 23, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            TimestampUTC = new DateTimeOffset(new DateTime(2022, 8, 31, 21, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            VolumeFee = 1.2f,
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 31,
                            Country = "SE",
                            ImbalanceFee = 1.15f,
                            PeakLoadFee = 0.32f,
                            Timestamp = new DateTimeOffset(new DateTime(2022, 11, 15, 23, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            TimestampUTC = new DateTimeOffset(new DateTime(2022, 11, 15, 22, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            VolumeFee = 0.85f,
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 32,
                            Country = "SE",
                            ImbalanceFee = 1.15f,
                            PeakLoadFee = 0.33f,
                            Timestamp = new DateTimeOffset(new DateTime(2022, 11, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            TimestampUTC = new DateTimeOffset(new DateTime(2022, 11, 15, 23, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            VolumeFee = 0.85f,
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 33,
                            Country = "FI",
                            ImbalanceFee = 1.15f,
                            Timestamp = new DateTimeOffset(new DateTime(2022, 12, 31, 23, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            TimestampUTC = new DateTimeOffset(new DateTime(2022, 12, 31, 22, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            VolumeFee = 1.7f,
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 34,
                            Country = "SE",
                            ImbalanceFee = 1.15f,
                            PeakLoadFee = 0.33f,
                            Timestamp = new DateTimeOffset(new DateTime(2022, 12, 31, 23, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            TimestampUTC = new DateTimeOffset(new DateTime(2022, 12, 31, 22, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            VolumeFee = 0.85f,
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 35,
                            Country = "SE",
                            ImbalanceFee = 1.15f,
                            PeakLoadFee = 0.33f,
                            Timestamp = new DateTimeOffset(new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            TimestampUTC = new DateTimeOffset(new DateTime(2022, 12, 31, 23, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            VolumeFee = 1.2f,
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 36,
                            Country = "FI",
                            ImbalanceFee = 1.15f,
                            Timestamp = new DateTimeOffset(new DateTime(2023, 4, 30, 22, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            TimestampUTC = new DateTimeOffset(new DateTime(2023, 4, 30, 20, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            VolumeFee = 1.7f,
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 37,
                            Country = "NO",
                            ImbalanceFee = 1.15f,
                            Timestamp = new DateTimeOffset(new DateTime(2023, 5, 21, 23, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            TimestampUTC = new DateTimeOffset(new DateTime(2023, 5, 21, 21, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            VolumeFee = 0.13f,
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 38,
                            Country = "FI",
                            ImbalanceFee = 1.15f,
                            Timestamp = new DateTimeOffset(new DateTime(2023, 5, 21, 23, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            TimestampUTC = new DateTimeOffset(new DateTime(2023, 5, 21, 21, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            VolumeFee = 1.2f,
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 39,
                            Country = "DK",
                            ImbalanceFee = 0.133f,
                            Timestamp = new DateTimeOffset(new DateTime(2023, 5, 21, 23, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            TimestampUTC = new DateTimeOffset(new DateTime(2023, 5, 21, 21, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 40,
                            Country = "SE",
                            ImbalanceFee = 1.15f,
                            PeakLoadFee = 0.33f,
                            Timestamp = new DateTimeOffset(new DateTime(2023, 5, 21, 23, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            TimestampUTC = new DateTimeOffset(new DateTime(2023, 5, 21, 21, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            VolumeFee = 1.2f,
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 41,
                            Country = "NO",
                            HourlyImbalanceFee = 1.15f,
                            Timestamp = new DateTimeOffset(new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            TimestampUTC = new DateTimeOffset(new DateTime(2023, 5, 31, 22, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            VolumeFee = 0.13f,
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 42,
                            Country = "SE",
                            HourlyImbalanceFee = 1.15f,
                            PeakLoadFee = 0.33f,
                            Timestamp = new DateTimeOffset(new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            TimestampUTC = new DateTimeOffset(new DateTime(2023, 5, 31, 22, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            VolumeFee = 1.2f,
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 43,
                            Country = "DK",
                            HourlyImbalanceFee = 0.133f,
                            Timestamp = new DateTimeOffset(new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            TimestampUTC = new DateTimeOffset(new DateTime(2023, 5, 31, 22, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 44,
                            Country = "FI",
                            HourlyImbalanceFee = 1.15f,
                            Timestamp = new DateTimeOffset(new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            TimestampUTC = new DateTimeOffset(new DateTime(2023, 5, 31, 22, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            VolumeFee = 1.2f,
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 45,
                            Country = "FI",
                            HourlyImbalanceFee = 1.15f,
                            Timestamp = new DateTimeOffset(new DateTime(2023, 10, 31, 22, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            TimestampUTC = new DateTimeOffset(new DateTime(2023, 10, 31, 21, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            VolumeFee = 1.2f,
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 46,
                            Country = "FI",
                            HourlyImbalanceFee = 1.15f,
                            Timestamp = new DateTimeOffset(new DateTime(2023, 10, 31, 23, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            TimestampUTC = new DateTimeOffset(new DateTime(2023, 10, 31, 22, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            VolumeFee = 1.5f,
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 47,
                            Country = "SE",
                            HourlyImbalanceFee = 1.15f,
                            PeakLoadFee = 0.33f,
                            Timestamp = new DateTimeOffset(new DateTime(2023, 11, 15, 23, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            TimestampUTC = new DateTimeOffset(new DateTime(2023, 11, 15, 22, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            VolumeFee = 1.2f,
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 48,
                            Country = "SE",
                            HourlyImbalanceFee = 1.15f,
                            PeakLoadFee = 0.29f,
                            Timestamp = new DateTimeOffset(new DateTime(2023, 11, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            TimestampUTC = new DateTimeOffset(new DateTime(2023, 11, 15, 23, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            VolumeFee = 1.2f,
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 49,
                            Country = "NO",
                            HourlyImbalanceFee = 1.15f,
                            Timestamp = new DateTimeOffset(new DateTime(2023, 12, 31, 23, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            TimestampUTC = new DateTimeOffset(new DateTime(2023, 12, 31, 22, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            VolumeFee = 0.13f,
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 50,
                            Country = "SE",
                            HourlyImbalanceFee = 1.15f,
                            PeakLoadFee = 0.29f,
                            Timestamp = new DateTimeOffset(new DateTime(2023, 12, 31, 23, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            TimestampUTC = new DateTimeOffset(new DateTime(2023, 12, 31, 22, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            VolumeFee = 1.2f,
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 51,
                            Country = "SE",
                            HourlyImbalanceFee = 1.15f,
                            PeakLoadFee = 0.29f,
                            Timestamp = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            TimestampUTC = new DateTimeOffset(new DateTime(2023, 12, 31, 23, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            VolumeFee = 1.6f,
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 52,
                            Country = "NO",
                            HourlyImbalanceFee = 1.15f,
                            Timestamp = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            TimestampUTC = new DateTimeOffset(new DateTime(2023, 12, 31, 23, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            VolumeFee = 0.21f,
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 53,
                            Country = "FI",
                            HourlyImbalanceFee = 1.15f,
                            Timestamp = new DateTimeOffset(new DateTime(2024, 2, 29, 22, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            TimestampUTC = new DateTimeOffset(new DateTime(2024, 2, 29, 21, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            VolumeFee = 1.5f,
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 54,
                            Country = "FI",
                            HourlyImbalanceFee = 1.15f,
                            Timestamp = new DateTimeOffset(new DateTime(2024, 2, 29, 23, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            TimestampUTC = new DateTimeOffset(new DateTime(2024, 2, 29, 22, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            VolumeFee = 1.33f,
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 55,
                            Country = "SE",
                            HourlyImbalanceFee = 1.15f,
                            PeakLoadFee = 0.29f,
                            Timestamp = new DateTimeOffset(new DateTime(2024, 9, 1, 23, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            TimestampUTC = new DateTimeOffset(new DateTime(2024, 9, 1, 21, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            VolumeFee = 1.6f,
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 56,
                            Country = "NO",
                            HourlyImbalanceFee = 1.15f,
                            Timestamp = new DateTimeOffset(new DateTime(2024, 9, 1, 23, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            TimestampUTC = new DateTimeOffset(new DateTime(2024, 9, 1, 21, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            VolumeFee = 0.21f,
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 57,
                            Country = "DK",
                            HourlyImbalanceFee = 0.133f,
                            Timestamp = new DateTimeOffset(new DateTime(2024, 9, 1, 23, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            TimestampUTC = new DateTimeOffset(new DateTime(2024, 9, 1, 21, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            WeeklyFee = 30
                        },
                        new
                        {
                            Id = 58,
                            Country = "FI",
                            HourlyImbalanceFee = 1.15f,
                            Timestamp = new DateTimeOffset(new DateTime(2024, 9, 1, 23, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            TimestampUTC = new DateTimeOffset(new DateTime(2024, 9, 1, 21, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            VolumeFee = 1.33f,
                            WeeklyFee = 30
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
